version: '3'

services:
  wordpress:
    image: fanswerss/wordpress:1.0
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - frontend-network
      - backend-network

  mariadb:
    image: fanswerss/mariadb:1.1
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  db_data: